"""
Synthetic data generator for AskKMITL PoC.
Generates a realistic student cohort with a latent behavioural→outcome
relationship that the at-risk model can recover (DR-1, DR-2).

Usage:
    python generate.py --seed 42 --students 500 --output-dir exports/
    python generate.py --seed 42 --students 500 --to-postgres
"""

import argparse
import hashlib
import json
import os
import random
import math
from datetime import datetime, date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

SEED_DIR = Path(__file__).parent / "seeds"
EXPORT_DIR = Path(__file__).parent / "exports"

TERMS = ["2022-1", "2022-2", "2023-1", "2023-2", "2024-1", "2024-2"]
GRADE_MAP = {
    4.0: "A", 3.5: "B+", 3.0: "B", 2.5: "C+",
    2.0: "C", 1.5: "D+", 1.0: "D", 0.0: "F",
}
WITHDRAWAL_QUERY_TOPICS = ["withdrawal", "deadline", "grade_anxiety", "registration"]
ANXIETY_TOPICS = ["grades", "grade_anxiety", "deadline", "scholarship", "gpa_simulation"]
ALL_TOPICS = [
    "registration", "thesis", "grades", "withdrawal", "deadline",
    "grade_anxiety", "scholarship", "curriculum", "credits",
    "gpa_simulation", "course_info", "other",
]


def load_seed(filename: str):
    with open(SEED_DIR / filename) as f:
        return json.load(f)


def sha256_hash(salt: str, student_id: str) -> str:
    return hashlib.sha256(f"{salt}{student_id}".encode()).hexdigest()


def sample_grade(ability: float, rng: np.random.Generator) -> tuple[str, float]:
    """Sample a grade given latent ability ∈ [0, 1]."""
    grade_points = [4.0, 3.5, 3.0, 2.5, 2.0, 1.5, 1.0, 0.0]
    # ability drives mean; add noise
    mean_gp = 1.0 + ability * 3.0
    raw = rng.normal(mean_gp, 0.6)
    raw = float(np.clip(raw, 0.0, 4.0))
    # snap to nearest grade point
    gp = min(grade_points, key=lambda g: abs(g - raw))
    return GRADE_MAP[gp], gp


def compute_gpax(grade_points_credits: list[tuple[float, int]]) -> float:
    total_credits = sum(c for _, c in grade_points_credits)
    if total_credits == 0:
        return 0.0
    total_points = sum(gp * c for gp, c in grade_points_credits)
    return round(total_points / total_credits, 3)


def gen_chat_events(
    student_id: str,
    student_hash: str,
    ability: float,
    stress_shock: bool,
    term: str,
    term_index: int,
    calendar_events: list[dict],
    consent: bool,
    rng: np.random.Generator,
) -> list[dict]:
    """
    Generate interaction log events for one student-term.
    Injects latent link: low-ability / stress-shocked students ask more
    withdrawal/anxiety queries near deadlines.
    """
    term_start = next((e["start_date"] for e in calendar_events
                       if e["term"] == term and e["event_type"] == "term_start"), None)
    withdrawal_dl = next((e["start_date"] for e in calendar_events
                          if e["term"] == term and e["event_type"] == "withdrawal_deadline"), None)
    if not term_start:
        return []

    start_dt = datetime.strptime(term_start, "%Y-%m-%d")
    term_duration_days = 110

    # Base query count increases with anxiety
    anxiety_level = max(0.0, 1.0 - ability) + (0.4 if stress_shock else 0.0)
    base_queries = rng.poisson(max(1, int(4 + anxiety_level * 12)))

    events = []
    for _ in range(int(base_queries)):
        # day offset within term
        day_offset = int(rng.integers(0, term_duration_days))
        # stressed students cluster queries near withdrawal deadline
        if withdrawal_dl and anxiety_level > 0.5 and rng.random() < 0.4:
            dl_dt = datetime.strptime(withdrawal_dl, "%Y-%m-%d")
            dl_offset = (dl_dt - start_dt).days
            day_offset = max(0, int(rng.normal(dl_offset, 7)))

        ts = start_dt + timedelta(days=day_offset, hours=int(rng.integers(8, 22)))

        # Topic distribution skewed by anxiety
        if anxiety_level > 0.5 and rng.random() < 0.6:
            topic = rng.choice(ANXIETY_TOPICS)
        else:
            topic = rng.choice(ALL_TOPICS)

        # Intent
        if topic in ("grades", "gpa_simulation", "credits"):
            intent = "personal_data" if rng.random() < 0.7 else "knowledge"
        elif topic in ("thesis", "scholarship", "curriculum", "course_info"):
            intent = "knowledge"
        else:
            intent = rng.choice(["knowledge", "personal_data", "other"])

        tier = "B" if intent == "personal_data" else "A"

        events.append({
            "event_id": None,  # UUID generated by DB / pandas
            "student_hash": student_hash,
            "ts": ts.isoformat(),
            "locale": "th" if rng.random() < 0.6 else "en",
            "raw_query": None if not consent else _fake_query(topic, rng),
            "intent": intent,
            "topic": topic,
            "tier_used": tier,
            "resolved": bool(rng.random() < 0.85),
            "escalated_to": None if rng.random() < 0.9 else "registrar",
            "latency_ms": int(rng.normal(1800, 400)),
            "retrieval_conf": round(float(rng.uniform(0.55, 0.98)), 3),
        })
    return events


def _fake_query(topic: str, rng: np.random.Generator) -> str:
    templates = {
        "withdrawal": ["วิธีถอนรายวิชาทำยังไง", "ถอนวิชาเกินกำหนดได้ไหม", "How do I withdraw from a course?"],
        "deadline":   ["กำหนดส่งคำร้องวันไหน", "Deadline for add/drop?", "วันสุดท้ายลงทะเบียนคือวันไหน"],
        "grades":     ["เกรดเทอมนี้ออกแล้วหรือยัง", "What is my current GPA?", "ดูเกรดได้ที่ไหน"],
        "grade_anxiety": ["ต้องได้เกรดเท่าไหร่ถึงไม่โดนพัก", "Will I be on probation?", "GPA ต่ำสุดที่ต้องได้คือเท่าไหร่"],
        "scholarship": ["ทุน กยศ. ต้องเกรดเท่าไหร่", "Scholarship GPA requirement?"],
        "thesis":     ["ขั้นตอนสอบวิทยานิพนธ์", "Thesis defense requirements", "ยื่นเล่มธีสิสเมื่อไหร่"],
        "registration": ["วิธีลงทะเบียนออนไลน์", "Registration steps", "ลงทะเบียนเพิ่มวิชาได้ไหม"],
        "curriculum": ["วิชาบังคับสำหรับสาขาฉัน", "Required courses for my program"],
        "credits":    ["เหลืออีกกี่หน่วยกิตถึงจบ", "How many credits left to graduate?"],
        "gpa_simulation": ["ถ้าได้ A ทุกวิชาเทอมนี้ GPAX จะเป็นเท่าไหร่", "Simulate my GPA"],
        "course_info": ["วิชา Data Mining มีสอนไหม", "Course description for Machine Learning"],
        "other":      ["ห้องสมุดเปิดกี่โมง", "Campus WiFi password?"],
    }
    pool = templates.get(topic, templates["other"])
    return str(rng.choice(pool))


def generate(
    n_students: int = 300,
    seed: int = 42,
    salt: str = "dev_salt",
    output_dir: Path = EXPORT_DIR,
) -> dict[str, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    random.seed(seed)

    programs = load_seed("programs.json")
    calendar = load_seed("calendar.json")

    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Students ──────────────────────────────────────────────────────────
    student_rows = []
    for i in range(1, n_students + 1):
        prog = random.choice(programs)
        admit_term_idx = int(rng.integers(0, 3))
        admit_term = TERMS[admit_term_idx]
        year_level = 1 + (len(TERMS) - 1 - admit_term_idx) // 2
        student_id = f"63{i:05d}"
        student_hash = sha256_hash(salt, student_id)
        consent = bool(rng.random() < 0.75)
        student_rows.append({
            "student_id": student_id,
            "student_hash": student_hash,
            "program_id": prog["program_id"],
            "year_level": min(year_level, 4),
            "admit_term": admit_term,
            "status": "active",
            "consent_analytics": consent,
            "ability": float(rng.beta(3, 2)),    # latent ability, NOT stored in DB
        })

    students_df = pd.DataFrame(student_rows)

    # ── Enrolments & Grades ───────────────────────────────────────────────
    enrolment_rows = []
    term_summary_rows = []
    chat_event_rows = []

    # Simple course pool (real courses come from curriculum seeds)
    course_ids = list(range(1, 31))  # placeholders until courses seeded

    for _, stu in students_df.iterrows():
        admit_idx = TERMS.index(stu["admit_term"])
        all_gp_credits: list[tuple[float, int]] = []
        stress_shock = rng.random() < 0.15  # 15% of students hit a stress event

        for term_idx, term in enumerate(TERMS[admit_idx:], start=admit_idx):
            n_courses = int(rng.integers(3, 6))
            term_courses = random.sample(course_ids, min(n_courses, len(course_ids)))

            term_gp_credits: list[tuple[float, int]] = []
            for cid in term_courses:
                grade_str, gp = sample_grade(stu["ability"], rng)
                credits = 3
                enrolment_rows.append({
                    "student_id": stu["student_id"],
                    "course_id": cid,
                    "term": term,
                    "grade": grade_str,
                    "grade_point": gp,
                    "status": "completed",
                    "credits": credits,
                })
                if grade_str not in ("F", "W"):
                    all_gp_credits.append((gp, credits))
                    term_gp_credits.append((gp, credits))

            term_gpa = compute_gpax(term_gp_credits) if term_gp_credits else 0.0
            gpax = compute_gpax(all_gp_credits) if all_gp_credits else 0.0
            credits_earned = sum(c for _, c in all_gp_credits)

            term_summary_rows.append({
                "student_id": stu["student_id"],
                "term": term,
                "term_gpa": term_gpa,
                "gpax": gpax,
                "credits_earned": credits_earned,
            })

            # Chat events for this term
            events = gen_chat_events(
                student_id=stu["student_id"],
                student_hash=stu["student_hash"],
                ability=stu["ability"],
                stress_shock=stress_shock,
                term=term,
                term_index=term_idx,
                calendar_events=calendar,
                consent=bool(stu["consent_analytics"]),
                rng=rng,
            )
            chat_event_rows.extend(events)

    students_out = students_df.drop(columns=["ability"])
    enrolments_df = pd.DataFrame(enrolment_rows)
    term_summary_df = pd.DataFrame(term_summary_rows)
    chat_events_df = pd.DataFrame(chat_event_rows)
    chat_events_df.index = range(len(chat_events_df))

    # Parquet exports (UTF-8, analytics plane)
    students_out.to_parquet(output_dir / "students.parquet", index=False)
    enrolments_df.to_parquet(output_dir / "enrolments.parquet", index=False)
    term_summary_df.to_parquet(output_dir / "term_summary.parquet", index=False)
    chat_events_df.to_parquet(output_dir / "chat_events.parquet", index=False)

    print(f"Generated {len(students_out)} students, "
          f"{len(enrolments_df)} enrolments, "
          f"{len(chat_events_df)} chat events.")
    print(f"Parquet files written to {output_dir}/")

    return {
        "students": students_out,
        "enrolments": enrolments_df,
        "term_summary": term_summary_df,
        "chat_events": chat_events_df,
    }


def to_postgres(dfs: dict[str, pd.DataFrame], database_url: str, salt: str = "dev_salt"):
    import sqlalchemy as sa

    engine = sa.create_engine(database_url)
    # Insert students (skip ability column, already dropped)
    dfs["students"].to_sql("students", engine, if_exists="append", index=False,
                           method="multi", chunksize=500)
    dfs["enrolments"].drop(columns=["credits"], errors="ignore").to_sql(
        "enrolments", engine, if_exists="append", index=False,
        method="multi", chunksize=1000)
    dfs["term_summary"].to_sql("term_summary", engine, if_exists="append", index=False,
                                method="multi", chunksize=1000)

    events = dfs["chat_events"].copy()
    events = events.drop(columns=["event_id"], errors="ignore")
    events.to_sql("chat_events", engine, if_exists="append", index=False,
                  method="multi", chunksize=1000)
    print("Data inserted into PostgreSQL.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AskKMITL synthetic data generator")
    parser.add_argument("--seed",       type=int,  default=42)
    parser.add_argument("--students",   type=int,  default=300)
    parser.add_argument("--salt",       type=str,  default=os.getenv("HASH_SALT", "dev_salt"))
    parser.add_argument("--output-dir", type=Path, default=EXPORT_DIR)
    parser.add_argument("--to-postgres", action="store_true")
    parser.add_argument("--database-url", type=str, default=os.getenv("DATABASE_URL", ""))
    args = parser.parse_args()

    dfs = generate(
        n_students=args.students,
        seed=args.seed,
        salt=args.salt,
        output_dir=args.output_dir,
    )

    if args.to_postgres:
        if not args.database_url:
            raise ValueError("--database-url or DATABASE_URL env var required")
        to_postgres(dfs, args.database_url, salt=args.salt)
